name: Deploy Bluroca Site

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true

      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install and Build 🔧
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          MANAGER_PASSWORD: ${{ secrets.MANAGER_PASSWORD }}
        run: |
          ADMIN_B64=$(echo -n "$ADMIN_PASSWORD" | base64)
          MANAGER_B64=$(echo -n "$MANAGER_PASSWORD" | base64)
          echo "env:" > _secrets.yml
          echo "  ADMIN_PASSWORD_B64: \"$ADMIN_B64\"" >> _secrets.yml
          echo "  MANAGER_PASSWORD_B64: \"$MANAGER_B64\"" >> _secrets.yml
          export JEKYLL_ENV=production
          bundle exec jekyll build --trace --verbose --config _config.yml,_secrets.yml

#      - name: Purge unused CSS 🧹
#        run: |
#          npm install -g purgecss
#          purgecss -c purgecss.config.js

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          cname: bluroca.com
          force_orphan: true
          verbose: true